// This is a generated file. Use and modify at your own risk.
////////////////////////////////////////////////////////////////////////////////
// Author: Kai Zhong
// Mail  : zhongkai2020@sina.com
// Date  : 2022.12.15
// Info  : generated by Vitis and nothing has been changed
//////////////////////////////////////////////////////////////////////////////// 
// default_nettype of none prevents implicit wire declaration.
`default_nettype none
`timescale 1 ps / 1 ps
import axi_vip_pkg::*;
import slv_inst_axi_vip_pkg::*;
import slv_weight_axi_vip_pkg::*;
import slv_bias_axi_vip_pkg::*;
import slv_feature_axi_vip_pkg::*;
import slv_adj_axi_vip_pkg::*;
import control_gnn_0_vip_pkg::*;
module gnn_0_tb ();
parameter integer LP_MAX_LENGTH = 8192;
parameter integer LP_MAX_TRANSFER_LENGTH = 16384 / 4;
parameter integer C_S_AXI_CONTROL_ADDR_WIDTH = 12;
parameter integer C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter integer C_INST_AXI_ADDR_WIDTH = 64;
parameter integer C_INST_AXI_DATA_WIDTH = 512;
parameter integer C_WEIGHT_AXI_ADDR_WIDTH = 64;
parameter integer C_WEIGHT_AXI_DATA_WIDTH = 512;
parameter integer C_BIAS_AXI_ADDR_WIDTH = 64;
parameter integer C_BIAS_AXI_DATA_WIDTH = 512;
parameter integer C_FEATURE_AXI_ADDR_WIDTH = 64;
parameter integer C_FEATURE_AXI_DATA_WIDTH = 512;
parameter integer C_ADJ_AXI_ADDR_WIDTH = 64;
parameter integer C_ADJ_AXI_DATA_WIDTH = 512;

// Control Register
parameter KRNL_CTRL_REG_ADDR     = 32'h00000000;
parameter CTRL_START_MASK        = 32'h00000001;
parameter CTRL_DONE_MASK         = 32'h00000002;
parameter CTRL_IDLE_MASK         = 32'h00000004;
parameter CTRL_READY_MASK        = 32'h00000008;
parameter CTRL_CONTINUE_MASK     = 32'h00000010; // Only ap_ctrl_chain
parameter CTRL_AUTO_RESTART_MASK = 32'h00000080; // Not used

// Global Interrupt Enable Register
parameter KRNL_GIE_REG_ADDR      = 32'h00000004;
parameter GIE_GIE_MASK           = 32'h00000001;
// IP Interrupt Enable Register
parameter KRNL_IER_REG_ADDR      = 32'h00000008;
parameter IER_DONE_MASK          = 32'h00000001;
parameter IER_READY_MASK         = 32'h00000002;
// IP Interrupt Status Register
parameter KRNL_ISR_REG_ADDR      = 32'h0000000c;
parameter ISR_DONE_MASK          = 32'h00000001;
parameter ISR_READY_MASK         = 32'h00000002;

parameter integer LP_CLK_PERIOD_PS = 4000; // 250 MHz

//System Signals
logic ap_clk = 0;

initial begin: AP_CLK
  forever begin
    ap_clk = #(LP_CLK_PERIOD_PS/2) ~ap_clk;
  end
end
 
//System Signals
logic ap_rst_n = 0;
logic initial_reset  =0;

task automatic ap_rst_n_sequence(input integer unsigned width = 20);
  @(posedge ap_clk);
  #1ps;
  ap_rst_n = 0;
  repeat (width) @(posedge ap_clk);
  #1ps;
  ap_rst_n = 1;
endtask

initial begin: AP_RST
  ap_rst_n_sequence(50);
  initial_reset =1;
end
//AXI4 master interface inst_axi
wire [1-1:0] inst_axi_awvalid;
wire [1-1:0] inst_axi_awready;
wire [C_INST_AXI_ADDR_WIDTH-1:0] inst_axi_awaddr;
wire [8-1:0] inst_axi_awlen;
wire [1-1:0] inst_axi_wvalid;
wire [1-1:0] inst_axi_wready;
wire [C_INST_AXI_DATA_WIDTH-1:0] inst_axi_wdata;
wire [C_INST_AXI_DATA_WIDTH/8-1:0] inst_axi_wstrb;
wire [1-1:0] inst_axi_wlast;
wire [1-1:0] inst_axi_bvalid;
wire [1-1:0] inst_axi_bready;
wire [1-1:0] inst_axi_arvalid;
wire [1-1:0] inst_axi_arready;
wire [C_INST_AXI_ADDR_WIDTH-1:0] inst_axi_araddr;
wire [8-1:0] inst_axi_arlen;
wire [1-1:0] inst_axi_rvalid;
wire [1-1:0] inst_axi_rready;
wire [C_INST_AXI_DATA_WIDTH-1:0] inst_axi_rdata;
wire [1-1:0] inst_axi_rlast;
//AXI4 master interface weight_axi
wire [1-1:0] weight_axi_awvalid;
wire [1-1:0] weight_axi_awready;
wire [C_WEIGHT_AXI_ADDR_WIDTH-1:0] weight_axi_awaddr;
wire [8-1:0] weight_axi_awlen;
wire [1-1:0] weight_axi_wvalid;
wire [1-1:0] weight_axi_wready;
wire [C_WEIGHT_AXI_DATA_WIDTH-1:0] weight_axi_wdata;
wire [C_WEIGHT_AXI_DATA_WIDTH/8-1:0] weight_axi_wstrb;
wire [1-1:0] weight_axi_wlast;
wire [1-1:0] weight_axi_bvalid;
wire [1-1:0] weight_axi_bready;
wire [1-1:0] weight_axi_arvalid;
wire [1-1:0] weight_axi_arready;
wire [C_WEIGHT_AXI_ADDR_WIDTH-1:0] weight_axi_araddr;
wire [8-1:0] weight_axi_arlen;
wire [1-1:0] weight_axi_rvalid;
wire [1-1:0] weight_axi_rready;
wire [C_WEIGHT_AXI_DATA_WIDTH-1:0] weight_axi_rdata;
wire [1-1:0] weight_axi_rlast;
//AXI4 master interface bias_axi
wire [1-1:0] bias_axi_awvalid;
wire [1-1:0] bias_axi_awready;
wire [C_BIAS_AXI_ADDR_WIDTH-1:0] bias_axi_awaddr;
wire [8-1:0] bias_axi_awlen;
wire [1-1:0] bias_axi_wvalid;
wire [1-1:0] bias_axi_wready;
wire [C_BIAS_AXI_DATA_WIDTH-1:0] bias_axi_wdata;
wire [C_BIAS_AXI_DATA_WIDTH/8-1:0] bias_axi_wstrb;
wire [1-1:0] bias_axi_wlast;
wire [1-1:0] bias_axi_bvalid;
wire [1-1:0] bias_axi_bready;
wire [1-1:0] bias_axi_arvalid;
wire [1-1:0] bias_axi_arready;
wire [C_BIAS_AXI_ADDR_WIDTH-1:0] bias_axi_araddr;
wire [8-1:0] bias_axi_arlen;
wire [1-1:0] bias_axi_rvalid;
wire [1-1:0] bias_axi_rready;
wire [C_BIAS_AXI_DATA_WIDTH-1:0] bias_axi_rdata;
wire [1-1:0] bias_axi_rlast;
//AXI4 master interface feature_axi
wire [1-1:0] feature_axi_awvalid;
wire [1-1:0] feature_axi_awready;
wire [C_FEATURE_AXI_ADDR_WIDTH-1:0] feature_axi_awaddr;
wire [8-1:0] feature_axi_awlen;
wire [1-1:0] feature_axi_wvalid;
wire [1-1:0] feature_axi_wready;
wire [C_FEATURE_AXI_DATA_WIDTH-1:0] feature_axi_wdata;
wire [C_FEATURE_AXI_DATA_WIDTH/8-1:0] feature_axi_wstrb;
wire [1-1:0] feature_axi_wlast;
wire [1-1:0] feature_axi_bvalid;
wire [1-1:0] feature_axi_bready;
wire [1-1:0] feature_axi_arvalid;
wire [1-1:0] feature_axi_arready;
wire [C_FEATURE_AXI_ADDR_WIDTH-1:0] feature_axi_araddr;
wire [8-1:0] feature_axi_arlen;
wire [1-1:0] feature_axi_rvalid;
wire [1-1:0] feature_axi_rready;
wire [C_FEATURE_AXI_DATA_WIDTH-1:0] feature_axi_rdata;
wire [1-1:0] feature_axi_rlast;
//AXI4 master interface adj_axi
wire [1-1:0] adj_axi_awvalid;
wire [1-1:0] adj_axi_awready;
wire [C_ADJ_AXI_ADDR_WIDTH-1:0] adj_axi_awaddr;
wire [8-1:0] adj_axi_awlen;
wire [1-1:0] adj_axi_wvalid;
wire [1-1:0] adj_axi_wready;
wire [C_ADJ_AXI_DATA_WIDTH-1:0] adj_axi_wdata;
wire [C_ADJ_AXI_DATA_WIDTH/8-1:0] adj_axi_wstrb;
wire [1-1:0] adj_axi_wlast;
wire [1-1:0] adj_axi_bvalid;
wire [1-1:0] adj_axi_bready;
wire [1-1:0] adj_axi_arvalid;
wire [1-1:0] adj_axi_arready;
wire [C_ADJ_AXI_ADDR_WIDTH-1:0] adj_axi_araddr;
wire [8-1:0] adj_axi_arlen;
wire [1-1:0] adj_axi_rvalid;
wire [1-1:0] adj_axi_rready;
wire [C_ADJ_AXI_DATA_WIDTH-1:0] adj_axi_rdata;
wire [1-1:0] adj_axi_rlast;
//AXI4LITE control signals
wire [1-1:0] s_axi_control_awvalid;
wire [1-1:0] s_axi_control_awready;
wire [C_S_AXI_CONTROL_ADDR_WIDTH-1:0] s_axi_control_awaddr;
wire [1-1:0] s_axi_control_wvalid;
wire [1-1:0] s_axi_control_wready;
wire [C_S_AXI_CONTROL_DATA_WIDTH-1:0] s_axi_control_wdata;
wire [C_S_AXI_CONTROL_DATA_WIDTH/8-1:0] s_axi_control_wstrb;
wire [1-1:0] s_axi_control_arvalid;
wire [1-1:0] s_axi_control_arready;
wire [C_S_AXI_CONTROL_ADDR_WIDTH-1:0] s_axi_control_araddr;
wire [1-1:0] s_axi_control_rvalid;
wire [1-1:0] s_axi_control_rready;
wire [C_S_AXI_CONTROL_DATA_WIDTH-1:0] s_axi_control_rdata;
wire [2-1:0] s_axi_control_rresp;
wire [1-1:0] s_axi_control_bvalid;
wire [1-1:0] s_axi_control_bready;
wire [2-1:0] s_axi_control_bresp;
wire interrupt;

// DUT instantiation
gnn_0 #(
  .C_S_AXI_CONTROL_ADDR_WIDTH ( C_S_AXI_CONTROL_ADDR_WIDTH ),
  .C_S_AXI_CONTROL_DATA_WIDTH ( C_S_AXI_CONTROL_DATA_WIDTH ),
  .C_INST_AXI_ADDR_WIDTH      ( C_INST_AXI_ADDR_WIDTH      ),
  .C_INST_AXI_DATA_WIDTH      ( C_INST_AXI_DATA_WIDTH      ),
  .C_WEIGHT_AXI_ADDR_WIDTH    ( C_WEIGHT_AXI_ADDR_WIDTH    ),
  .C_WEIGHT_AXI_DATA_WIDTH    ( C_WEIGHT_AXI_DATA_WIDTH    ),
  .C_BIAS_AXI_ADDR_WIDTH      ( C_BIAS_AXI_ADDR_WIDTH      ),
  .C_BIAS_AXI_DATA_WIDTH      ( C_BIAS_AXI_DATA_WIDTH      ),
  .C_FEATURE_AXI_ADDR_WIDTH   ( C_FEATURE_AXI_ADDR_WIDTH   ),
  .C_FEATURE_AXI_DATA_WIDTH   ( C_FEATURE_AXI_DATA_WIDTH   ),
  .C_ADJ_AXI_ADDR_WIDTH       ( C_ADJ_AXI_ADDR_WIDTH       ),
  .C_ADJ_AXI_DATA_WIDTH       ( C_ADJ_AXI_DATA_WIDTH       )
)
inst_dut (
  .ap_clk                ( ap_clk                ),
  .ap_rst_n              ( ap_rst_n              ),
  .inst_axi_awvalid      ( inst_axi_awvalid      ),
  .inst_axi_awready      ( inst_axi_awready      ),
  .inst_axi_awaddr       ( inst_axi_awaddr       ),
  .inst_axi_awlen        ( inst_axi_awlen        ),
  .inst_axi_wvalid       ( inst_axi_wvalid       ),
  .inst_axi_wready       ( inst_axi_wready       ),
  .inst_axi_wdata        ( inst_axi_wdata        ),
  .inst_axi_wstrb        ( inst_axi_wstrb        ),
  .inst_axi_wlast        ( inst_axi_wlast        ),
  .inst_axi_bvalid       ( inst_axi_bvalid       ),
  .inst_axi_bready       ( inst_axi_bready       ),
  .inst_axi_arvalid      ( inst_axi_arvalid      ),
  .inst_axi_arready      ( inst_axi_arready      ),
  .inst_axi_araddr       ( inst_axi_araddr       ),
  .inst_axi_arlen        ( inst_axi_arlen        ),
  .inst_axi_rvalid       ( inst_axi_rvalid       ),
  .inst_axi_rready       ( inst_axi_rready       ),
  .inst_axi_rdata        ( inst_axi_rdata        ),
  .inst_axi_rlast        ( inst_axi_rlast        ),
  .weight_axi_awvalid    ( weight_axi_awvalid    ),
  .weight_axi_awready    ( weight_axi_awready    ),
  .weight_axi_awaddr     ( weight_axi_awaddr     ),
  .weight_axi_awlen      ( weight_axi_awlen      ),
  .weight_axi_wvalid     ( weight_axi_wvalid     ),
  .weight_axi_wready     ( weight_axi_wready     ),
  .weight_axi_wdata      ( weight_axi_wdata      ),
  .weight_axi_wstrb      ( weight_axi_wstrb      ),
  .weight_axi_wlast      ( weight_axi_wlast      ),
  .weight_axi_bvalid     ( weight_axi_bvalid     ),
  .weight_axi_bready     ( weight_axi_bready     ),
  .weight_axi_arvalid    ( weight_axi_arvalid    ),
  .weight_axi_arready    ( weight_axi_arready    ),
  .weight_axi_araddr     ( weight_axi_araddr     ),
  .weight_axi_arlen      ( weight_axi_arlen      ),
  .weight_axi_rvalid     ( weight_axi_rvalid     ),
  .weight_axi_rready     ( weight_axi_rready     ),
  .weight_axi_rdata      ( weight_axi_rdata      ),
  .weight_axi_rlast      ( weight_axi_rlast      ),
  .bias_axi_awvalid      ( bias_axi_awvalid      ),
  .bias_axi_awready      ( bias_axi_awready      ),
  .bias_axi_awaddr       ( bias_axi_awaddr       ),
  .bias_axi_awlen        ( bias_axi_awlen        ),
  .bias_axi_wvalid       ( bias_axi_wvalid       ),
  .bias_axi_wready       ( bias_axi_wready       ),
  .bias_axi_wdata        ( bias_axi_wdata        ),
  .bias_axi_wstrb        ( bias_axi_wstrb        ),
  .bias_axi_wlast        ( bias_axi_wlast        ),
  .bias_axi_bvalid       ( bias_axi_bvalid       ),
  .bias_axi_bready       ( bias_axi_bready       ),
  .bias_axi_arvalid      ( bias_axi_arvalid      ),
  .bias_axi_arready      ( bias_axi_arready      ),
  .bias_axi_araddr       ( bias_axi_araddr       ),
  .bias_axi_arlen        ( bias_axi_arlen        ),
  .bias_axi_rvalid       ( bias_axi_rvalid       ),
  .bias_axi_rready       ( bias_axi_rready       ),
  .bias_axi_rdata        ( bias_axi_rdata        ),
  .bias_axi_rlast        ( bias_axi_rlast        ),
  .feature_axi_awvalid   ( feature_axi_awvalid   ),
  .feature_axi_awready   ( feature_axi_awready   ),
  .feature_axi_awaddr    ( feature_axi_awaddr    ),
  .feature_axi_awlen     ( feature_axi_awlen     ),
  .feature_axi_wvalid    ( feature_axi_wvalid    ),
  .feature_axi_wready    ( feature_axi_wready    ),
  .feature_axi_wdata     ( feature_axi_wdata     ),
  .feature_axi_wstrb     ( feature_axi_wstrb     ),
  .feature_axi_wlast     ( feature_axi_wlast     ),
  .feature_axi_bvalid    ( feature_axi_bvalid    ),
  .feature_axi_bready    ( feature_axi_bready    ),
  .feature_axi_arvalid   ( feature_axi_arvalid   ),
  .feature_axi_arready   ( feature_axi_arready   ),
  .feature_axi_araddr    ( feature_axi_araddr    ),
  .feature_axi_arlen     ( feature_axi_arlen     ),
  .feature_axi_rvalid    ( feature_axi_rvalid    ),
  .feature_axi_rready    ( feature_axi_rready    ),
  .feature_axi_rdata     ( feature_axi_rdata     ),
  .feature_axi_rlast     ( feature_axi_rlast     ),
  .adj_axi_awvalid       ( adj_axi_awvalid       ),
  .adj_axi_awready       ( adj_axi_awready       ),
  .adj_axi_awaddr        ( adj_axi_awaddr        ),
  .adj_axi_awlen         ( adj_axi_awlen         ),
  .adj_axi_wvalid        ( adj_axi_wvalid        ),
  .adj_axi_wready        ( adj_axi_wready        ),
  .adj_axi_wdata         ( adj_axi_wdata         ),
  .adj_axi_wstrb         ( adj_axi_wstrb         ),
  .adj_axi_wlast         ( adj_axi_wlast         ),
  .adj_axi_bvalid        ( adj_axi_bvalid        ),
  .adj_axi_bready        ( adj_axi_bready        ),
  .adj_axi_arvalid       ( adj_axi_arvalid       ),
  .adj_axi_arready       ( adj_axi_arready       ),
  .adj_axi_araddr        ( adj_axi_araddr        ),
  .adj_axi_arlen         ( adj_axi_arlen         ),
  .adj_axi_rvalid        ( adj_axi_rvalid        ),
  .adj_axi_rready        ( adj_axi_rready        ),
  .adj_axi_rdata         ( adj_axi_rdata         ),
  .adj_axi_rlast         ( adj_axi_rlast         ),
  .s_axi_control_awvalid ( s_axi_control_awvalid ),
  .s_axi_control_awready ( s_axi_control_awready ),
  .s_axi_control_awaddr  ( s_axi_control_awaddr  ),
  .s_axi_control_wvalid  ( s_axi_control_wvalid  ),
  .s_axi_control_wready  ( s_axi_control_wready  ),
  .s_axi_control_wdata   ( s_axi_control_wdata   ),
  .s_axi_control_wstrb   ( s_axi_control_wstrb   ),
  .s_axi_control_arvalid ( s_axi_control_arvalid ),
  .s_axi_control_arready ( s_axi_control_arready ),
  .s_axi_control_araddr  ( s_axi_control_araddr  ),
  .s_axi_control_rvalid  ( s_axi_control_rvalid  ),
  .s_axi_control_rready  ( s_axi_control_rready  ),
  .s_axi_control_rdata   ( s_axi_control_rdata   ),
  .s_axi_control_rresp   ( s_axi_control_rresp   ),
  .s_axi_control_bvalid  ( s_axi_control_bvalid  ),
  .s_axi_control_bready  ( s_axi_control_bready  ),
  .s_axi_control_bresp   ( s_axi_control_bresp   ),
  .interrupt             ( interrupt             )
);

// Master Control instantiation
control_gnn_0_vip inst_control_gnn_0_vip (
  .aclk          ( ap_clk                ),
  .aresetn       ( ap_rst_n              ),
  .m_axi_awvalid ( s_axi_control_awvalid ),
  .m_axi_awready ( s_axi_control_awready ),
  .m_axi_awaddr  ( s_axi_control_awaddr  ),
  .m_axi_wvalid  ( s_axi_control_wvalid  ),
  .m_axi_wready  ( s_axi_control_wready  ),
  .m_axi_wdata   ( s_axi_control_wdata   ),
  .m_axi_wstrb   ( s_axi_control_wstrb   ),
  .m_axi_arvalid ( s_axi_control_arvalid ),
  .m_axi_arready ( s_axi_control_arready ),
  .m_axi_araddr  ( s_axi_control_araddr  ),
  .m_axi_rvalid  ( s_axi_control_rvalid  ),
  .m_axi_rready  ( s_axi_control_rready  ),
  .m_axi_rdata   ( s_axi_control_rdata   ),
  .m_axi_rresp   ( s_axi_control_rresp   ),
  .m_axi_bvalid  ( s_axi_control_bvalid  ),
  .m_axi_bready  ( s_axi_control_bready  ),
  .m_axi_bresp   ( s_axi_control_bresp   )
);

control_gnn_0_vip_mst_t  ctrl;

// Slave MM VIP instantiation
slv_inst_axi_vip inst_slv_inst_axi_vip (
  .aclk          ( ap_clk           ),
  .aresetn       ( ap_rst_n         ),
  .s_axi_awvalid ( inst_axi_awvalid ),
  .s_axi_awready ( inst_axi_awready ),
  .s_axi_awaddr  ( inst_axi_awaddr  ),
  .s_axi_awlen   ( inst_axi_awlen   ),
  .s_axi_wvalid  ( inst_axi_wvalid  ),
  .s_axi_wready  ( inst_axi_wready  ),
  .s_axi_wdata   ( inst_axi_wdata   ),
  .s_axi_wstrb   ( inst_axi_wstrb   ),
  .s_axi_wlast   ( inst_axi_wlast   ),
  .s_axi_bvalid  ( inst_axi_bvalid  ),
  .s_axi_bready  ( inst_axi_bready  ),
  .s_axi_arvalid ( inst_axi_arvalid ),
  .s_axi_arready ( inst_axi_arready ),
  .s_axi_araddr  ( inst_axi_araddr  ),
  .s_axi_arlen   ( inst_axi_arlen   ),
  .s_axi_rvalid  ( inst_axi_rvalid  ),
  .s_axi_rready  ( inst_axi_rready  ),
  .s_axi_rdata   ( inst_axi_rdata   ),
  .s_axi_rlast   ( inst_axi_rlast   )
);


slv_inst_axi_vip_slv_mem_t   inst_axi;
slv_inst_axi_vip_slv_t   inst_axi_slv;

// Slave MM VIP instantiation
slv_weight_axi_vip inst_slv_weight_axi_vip (
  .aclk          ( ap_clk             ),
  .aresetn       ( ap_rst_n           ),
  .s_axi_awvalid ( weight_axi_awvalid ),
  .s_axi_awready ( weight_axi_awready ),
  .s_axi_awaddr  ( weight_axi_awaddr  ),
  .s_axi_awlen   ( weight_axi_awlen   ),
  .s_axi_wvalid  ( weight_axi_wvalid  ),
  .s_axi_wready  ( weight_axi_wready  ),
  .s_axi_wdata   ( weight_axi_wdata   ),
  .s_axi_wstrb   ( weight_axi_wstrb   ),
  .s_axi_wlast   ( weight_axi_wlast   ),
  .s_axi_bvalid  ( weight_axi_bvalid  ),
  .s_axi_bready  ( weight_axi_bready  ),
  .s_axi_arvalid ( weight_axi_arvalid ),
  .s_axi_arready ( weight_axi_arready ),
  .s_axi_araddr  ( weight_axi_araddr  ),
  .s_axi_arlen   ( weight_axi_arlen   ),
  .s_axi_rvalid  ( weight_axi_rvalid  ),
  .s_axi_rready  ( weight_axi_rready  ),
  .s_axi_rdata   ( weight_axi_rdata   ),
  .s_axi_rlast   ( weight_axi_rlast   )
);


slv_weight_axi_vip_slv_mem_t   weight_axi;
slv_weight_axi_vip_slv_t   weight_axi_slv;

// Slave MM VIP instantiation
slv_bias_axi_vip inst_slv_bias_axi_vip (
  .aclk          ( ap_clk           ),
  .aresetn       ( ap_rst_n         ),
  .s_axi_awvalid ( bias_axi_awvalid ),
  .s_axi_awready ( bias_axi_awready ),
  .s_axi_awaddr  ( bias_axi_awaddr  ),
  .s_axi_awlen   ( bias_axi_awlen   ),
  .s_axi_wvalid  ( bias_axi_wvalid  ),
  .s_axi_wready  ( bias_axi_wready  ),
  .s_axi_wdata   ( bias_axi_wdata   ),
  .s_axi_wstrb   ( bias_axi_wstrb   ),
  .s_axi_wlast   ( bias_axi_wlast   ),
  .s_axi_bvalid  ( bias_axi_bvalid  ),
  .s_axi_bready  ( bias_axi_bready  ),
  .s_axi_arvalid ( bias_axi_arvalid ),
  .s_axi_arready ( bias_axi_arready ),
  .s_axi_araddr  ( bias_axi_araddr  ),
  .s_axi_arlen   ( bias_axi_arlen   ),
  .s_axi_rvalid  ( bias_axi_rvalid  ),
  .s_axi_rready  ( bias_axi_rready  ),
  .s_axi_rdata   ( bias_axi_rdata   ),
  .s_axi_rlast   ( bias_axi_rlast   )
);


slv_bias_axi_vip_slv_mem_t   bias_axi;
slv_bias_axi_vip_slv_t   bias_axi_slv;

// Slave MM VIP instantiation
slv_feature_axi_vip inst_slv_feature_axi_vip (
  .aclk          ( ap_clk              ),
  .aresetn       ( ap_rst_n            ),
  .s_axi_awvalid ( feature_axi_awvalid ),
  .s_axi_awready ( feature_axi_awready ),
  .s_axi_awaddr  ( feature_axi_awaddr  ),
  .s_axi_awlen   ( feature_axi_awlen   ),
  .s_axi_wvalid  ( feature_axi_wvalid  ),
  .s_axi_wready  ( feature_axi_wready  ),
  .s_axi_wdata   ( feature_axi_wdata   ),
  .s_axi_wstrb   ( feature_axi_wstrb   ),
  .s_axi_wlast   ( feature_axi_wlast   ),
  .s_axi_bvalid  ( feature_axi_bvalid  ),
  .s_axi_bready  ( feature_axi_bready  ),
  .s_axi_arvalid ( feature_axi_arvalid ),
  .s_axi_arready ( feature_axi_arready ),
  .s_axi_araddr  ( feature_axi_araddr  ),
  .s_axi_arlen   ( feature_axi_arlen   ),
  .s_axi_rvalid  ( feature_axi_rvalid  ),
  .s_axi_rready  ( feature_axi_rready  ),
  .s_axi_rdata   ( feature_axi_rdata   ),
  .s_axi_rlast   ( feature_axi_rlast   )
);


slv_feature_axi_vip_slv_mem_t   feature_axi;
slv_feature_axi_vip_slv_t   feature_axi_slv;

// Slave MM VIP instantiation
slv_adj_axi_vip inst_slv_adj_axi_vip (
  .aclk          ( ap_clk          ),
  .aresetn       ( ap_rst_n        ),
  .s_axi_awvalid ( adj_axi_awvalid ),
  .s_axi_awready ( adj_axi_awready ),
  .s_axi_awaddr  ( adj_axi_awaddr  ),
  .s_axi_awlen   ( adj_axi_awlen   ),
  .s_axi_wvalid  ( adj_axi_wvalid  ),
  .s_axi_wready  ( adj_axi_wready  ),
  .s_axi_wdata   ( adj_axi_wdata   ),
  .s_axi_wstrb   ( adj_axi_wstrb   ),
  .s_axi_wlast   ( adj_axi_wlast   ),
  .s_axi_bvalid  ( adj_axi_bvalid  ),
  .s_axi_bready  ( adj_axi_bready  ),
  .s_axi_arvalid ( adj_axi_arvalid ),
  .s_axi_arready ( adj_axi_arready ),
  .s_axi_araddr  ( adj_axi_araddr  ),
  .s_axi_arlen   ( adj_axi_arlen   ),
  .s_axi_rvalid  ( adj_axi_rvalid  ),
  .s_axi_rready  ( adj_axi_rready  ),
  .s_axi_rdata   ( adj_axi_rdata   ),
  .s_axi_rlast   ( adj_axi_rlast   )
);


slv_adj_axi_vip_slv_mem_t   adj_axi;
slv_adj_axi_vip_slv_t   adj_axi_slv;

parameter NUM_AXIS_MST = 0;
parameter NUM_AXIS_SLV = 0;

bit               error_found = 0;

///////////////////////////////////////////////////////////////////////////
// Pointer for interface : inst_axi
bit [63:0] inst_addr_ptr = 64'h0;

///////////////////////////////////////////////////////////////////////////
// Pointer for interface : weight_axi
bit [63:0] weight_addr_ptr = 64'h0;

///////////////////////////////////////////////////////////////////////////
// Pointer for interface : bias_axi
bit [63:0] bias_addr_ptr = 64'h0;

///////////////////////////////////////////////////////////////////////////
// Pointer for interface : feature_axi
bit [63:0] feature_addr_ptr = 64'h0;

///////////////////////////////////////////////////////////////////////////
// Pointer for interface : adj_axi
bit [63:0] adj_addr_ptr = 64'h0;

/////////////////////////////////////////////////////////////////////////////////////////////////
// Backdoor fill the inst_axi memory.
function void inst_axi_fill_memory(
  input bit [63:0] ptr,
  input integer    length
);
  for (longint unsigned slot = 0; slot < length; slot++) begin
    inst_axi.mem_model.backdoor_memory_write_4byte(ptr + (slot * 4), slot);
  end
endfunction

/////////////////////////////////////////////////////////////////////////////////////////////////
// Backdoor fill the weight_axi memory.
function void weight_axi_fill_memory(
  input bit [63:0] ptr,
  input integer    length
);
  for (longint unsigned slot = 0; slot < length; slot++) begin
    weight_axi.mem_model.backdoor_memory_write_4byte(ptr + (slot * 4), slot);
  end
endfunction

/////////////////////////////////////////////////////////////////////////////////////////////////
// Backdoor fill the bias_axi memory.
function void bias_axi_fill_memory(
  input bit [63:0] ptr,
  input integer    length
);
  for (longint unsigned slot = 0; slot < length; slot++) begin
    bias_axi.mem_model.backdoor_memory_write_4byte(ptr + (slot * 4), slot);
  end
endfunction

/////////////////////////////////////////////////////////////////////////////////////////////////
// Backdoor fill the feature_axi memory.
function void feature_axi_fill_memory(
  input bit [63:0] ptr,
  input integer    length
);
  for (longint unsigned slot = 0; slot < length; slot++) begin
    feature_axi.mem_model.backdoor_memory_write_4byte(ptr + (slot * 4), slot);
  end
endfunction

/////////////////////////////////////////////////////////////////////////////////////////////////
// Backdoor fill the adj_axi memory.
function void adj_axi_fill_memory(
  input bit [63:0] ptr,
  input integer    length
);
  for (longint unsigned slot = 0; slot < length; slot++) begin
    adj_axi.mem_model.backdoor_memory_write_4byte(ptr + (slot * 4), slot);
  end
endfunction

task automatic system_reset_sequence(input integer unsigned width = 20);
  $display("%t : Starting System Reset Sequence", $time);
  fork
    ap_rst_n_sequence(25);
    
  join

endtask


/////////////////////////////////////////////////////////////////////////////////////////////////
// Generate a random 32bit number
function bit [31:0] get_random_4bytes();
  bit [31:0] rptr;
  ptr_random_failed: assert(std::randomize(rptr));
  return(rptr);
endfunction

/////////////////////////////////////////////////////////////////////////////////////////////////
// Generate a random 64bit 4k aligned address pointer.
function bit [63:0] get_random_ptr();
  bit [63:0] rptr;
  ptr_random_failed: assert(std::randomize(rptr));
  rptr[31:0] &= ~(32'h00000fff);
  return(rptr);
endfunction

/////////////////////////////////////////////////////////////////////////////////////////////////
// Control interface non-blocking write
// The task will return when the transaction has been accepted by the driver. It will be some
// amount of time before it will appear on the interface.
task automatic write_register (input bit [31:0] addr_in, input bit [31:0] data);
  axi_transaction   wr_xfer;
  wr_xfer = ctrl.wr_driver.create_transaction("wr_xfer");
  assert(wr_xfer.randomize() with {addr == addr_in;});
  wr_xfer.set_data_beat(0, data);
  ctrl.wr_driver.send(wr_xfer);
endtask

/////////////////////////////////////////////////////////////////////////////////////////////////
// Control interface blocking write
// The task will return when the BRESP has been returned from the kernel.
task automatic blocking_write_register (input bit [31:0] addr_in, input bit [31:0] data);
  axi_transaction   wr_xfer;
  axi_transaction   wr_rsp;
  wr_xfer = ctrl.wr_driver.create_transaction("wr_xfer");
  wr_xfer.set_driver_return_item_policy(XIL_AXI_PAYLOAD_RETURN);
  assert(wr_xfer.randomize() with {addr == addr_in;});
  wr_xfer.set_data_beat(0, data);
  ctrl.wr_driver.send(wr_xfer);
  ctrl.wr_driver.wait_rsp(wr_rsp);
endtask

/////////////////////////////////////////////////////////////////////////////////////////////////
// Control interface blocking read
// The task will return when the BRESP has been returned from the kernel.
task automatic read_register (input bit [31:0] addr, output bit [31:0] rddata);
  axi_transaction   rd_xfer;
  axi_transaction   rd_rsp;
  bit [31:0] rd_value;
  rd_xfer = ctrl.rd_driver.create_transaction("rd_xfer");
  rd_xfer.set_addr(addr);
  rd_xfer.set_driver_return_item_policy(XIL_AXI_PAYLOAD_RETURN);
  ctrl.rd_driver.send(rd_xfer);
  ctrl.rd_driver.wait_rsp(rd_rsp);
  rd_value = rd_rsp.get_data_beat(0);
  rddata = rd_value;
endtask



/////////////////////////////////////////////////////////////////////////////////////////////////
// Poll the Control interface status register.
// This will poll until the DONE flag in the status register is asserted.
task automatic poll_done_register ();
  bit [31:0] rd_value;
  do begin
    read_register(KRNL_CTRL_REG_ADDR, rd_value);
  end while ((rd_value & CTRL_DONE_MASK) == 0);
endtask

// This will poll until the IDLE flag in the status register is asserted.
task automatic poll_idle_register ();
  bit [31:0] rd_value;
  do begin
    read_register(KRNL_CTRL_REG_ADDR, rd_value);
  end while ((rd_value & CTRL_IDLE_MASK) == 0);
endtask

/////////////////////////////////////////////////////////////////////////////////////////////////
// Write to the control registers to enable the triggering of interrupts for the kernel
task automatic enable_interrupts();
  $display("Starting: Enabling Interrupts....");
  write_register(KRNL_GIE_REG_ADDR, GIE_GIE_MASK);
  write_register(KRNL_IER_REG_ADDR, IER_DONE_MASK);
  $display("Finished: Interrupts enabled.");
endtask

/////////////////////////////////////////////////////////////////////////////////////////////////
// Disabled the interrupts.
task automatic disable_interrupts();
  $display("Starting: Disable Interrupts....");
  write_register(KRNL_GIE_REG_ADDR, 32'h0);
  write_register(KRNL_IER_REG_ADDR, 32'h0);
  $display("Finished: Interrupts disabled.");
endtask

/////////////////////////////////////////////////////////////////////////////////////////////////
//When the interrupt is asserted, read the correct registers and clear the asserted interrupt.
task automatic service_interrupts();
  bit [31:0] rd_value;
  $display("Starting Servicing interrupts....");
  read_register(KRNL_CTRL_REG_ADDR, rd_value);
  $display("Control Register: 0x%0x", rd_value);

  blocking_write_register(KRNL_CTRL_REG_ADDR, rd_value);

  if ((rd_value & CTRL_DONE_MASK) == 0) begin
    $error("%t : DONE bit not asserted. Register value: (0x%0x)", $time, rd_value);
  end
  read_register(KRNL_ISR_REG_ADDR, rd_value);
  $display("Interrupt Status Register: 0x%0x", rd_value);
  blocking_write_register(KRNL_ISR_REG_ADDR, rd_value);
  $display("Finished Servicing interrupts");
endtask

/////////////////////////////////////////////////////////////////////////////////////////////////
// Start the control VIP, SLAVE memory models and AXI4-Stream.
task automatic start_vips();

  $display("///////////////////////////////////////////////////////////////////////////");
  $display("Control Master: ctrl");
  ctrl = new("ctrl", gnn_0_tb.inst_control_gnn_0_vip.inst.IF);
  ctrl.start_master();

  $display("///////////////////////////////////////////////////////////////////////////");
  $display("Starting Memory slave: inst_axi");
  inst_axi = new("inst_axi", gnn_0_tb.inst_slv_inst_axi_vip.inst.IF);
  inst_axi.start_slave();

  $display("///////////////////////////////////////////////////////////////////////////");
  $display("Starting Memory slave: weight_axi");
  weight_axi = new("weight_axi", gnn_0_tb.inst_slv_weight_axi_vip.inst.IF);
  weight_axi.start_slave();

  $display("///////////////////////////////////////////////////////////////////////////");
  $display("Starting Memory slave: bias_axi");
  bias_axi = new("bias_axi", gnn_0_tb.inst_slv_bias_axi_vip.inst.IF);
  bias_axi.start_slave();

  $display("///////////////////////////////////////////////////////////////////////////");
  $display("Starting Memory slave: feature_axi");
  feature_axi = new("feature_axi", gnn_0_tb.inst_slv_feature_axi_vip.inst.IF);
  feature_axi.start_slave();

  $display("///////////////////////////////////////////////////////////////////////////");
  $display("Starting Memory slave: adj_axi");
  adj_axi = new("adj_axi", gnn_0_tb.inst_slv_adj_axi_vip.inst.IF);
  adj_axi.start_slave();

endtask

/////////////////////////////////////////////////////////////////////////////////////////////////
// For each of the connected slave interfaces, set the Slave to not de-assert WREADY at any time.
// This will show the fastest outbound bandwidth from the WRITE channel.
task automatic slv_no_backpressure_wready();
  axi_ready_gen     rgen;
  $display("%t - Applying slv_no_backpressure_wready", $time);

  rgen = new("inst_axi_no_backpressure_wready");
  rgen.set_ready_policy(XIL_AXI_READY_GEN_NO_BACKPRESSURE);
  inst_axi.wr_driver.set_wready_gen(rgen);

  rgen = new("weight_axi_no_backpressure_wready");
  rgen.set_ready_policy(XIL_AXI_READY_GEN_NO_BACKPRESSURE);
  weight_axi.wr_driver.set_wready_gen(rgen);

  rgen = new("bias_axi_no_backpressure_wready");
  rgen.set_ready_policy(XIL_AXI_READY_GEN_NO_BACKPRESSURE);
  bias_axi.wr_driver.set_wready_gen(rgen);

  rgen = new("feature_axi_no_backpressure_wready");
  rgen.set_ready_policy(XIL_AXI_READY_GEN_NO_BACKPRESSURE);
  feature_axi.wr_driver.set_wready_gen(rgen);

  rgen = new("adj_axi_no_backpressure_wready");
  rgen.set_ready_policy(XIL_AXI_READY_GEN_NO_BACKPRESSURE);
  adj_axi.wr_driver.set_wready_gen(rgen);

endtask


/////////////////////////////////////////////////////////////////////////////////////////////////
// For each of the connected slave interfaces, apply a WREADY policy to introduce backpressure.
// Based on the simulation seed the order/shape of the WREADY per-channel will be different.
task automatic slv_random_backpressure_wready();
  axi_ready_gen     rgen;
  $display("%t - Applying slv_random_backpressure_wready", $time);

  rgen = new("inst_axi_random_backpressure_wready");
  rgen.set_ready_policy(XIL_AXI_READY_GEN_RANDOM);
  rgen.set_low_time_range(0,12);
  rgen.set_high_time_range(1,12);
  rgen.set_event_count_range(3,5);
  inst_axi.wr_driver.set_wready_gen(rgen);

  rgen = new("weight_axi_random_backpressure_wready");
  rgen.set_ready_policy(XIL_AXI_READY_GEN_RANDOM);
  rgen.set_low_time_range(0,12);
  rgen.set_high_time_range(1,12);
  rgen.set_event_count_range(3,5);
  weight_axi.wr_driver.set_wready_gen(rgen);

  rgen = new("bias_axi_random_backpressure_wready");
  rgen.set_ready_policy(XIL_AXI_READY_GEN_RANDOM);
  rgen.set_low_time_range(0,12);
  rgen.set_high_time_range(1,12);
  rgen.set_event_count_range(3,5);
  bias_axi.wr_driver.set_wready_gen(rgen);

  rgen = new("feature_axi_random_backpressure_wready");
  rgen.set_ready_policy(XIL_AXI_READY_GEN_RANDOM);
  rgen.set_low_time_range(0,12);
  rgen.set_high_time_range(1,12);
  rgen.set_event_count_range(3,5);
  feature_axi.wr_driver.set_wready_gen(rgen);

  rgen = new("adj_axi_random_backpressure_wready");
  rgen.set_ready_policy(XIL_AXI_READY_GEN_RANDOM);
  rgen.set_low_time_range(0,12);
  rgen.set_high_time_range(1,12);
  rgen.set_event_count_range(3,5);
  adj_axi.wr_driver.set_wready_gen(rgen);

endtask


/////////////////////////////////////////////////////////////////////////////////////////////////
// For each of the connected slave interfaces, force the memory model to not insert any inter-beat
// gaps on the READ channel.
task automatic slv_no_delay_rvalid();
  $display("%t - Applying slv_no_delay_rvalid", $time);

  inst_axi.mem_model.set_inter_beat_gap_delay_policy(XIL_AXI_MEMORY_DELAY_FIXED);
  inst_axi.mem_model.set_inter_beat_gap(0);

  weight_axi.mem_model.set_inter_beat_gap_delay_policy(XIL_AXI_MEMORY_DELAY_FIXED);
  weight_axi.mem_model.set_inter_beat_gap(0);

  bias_axi.mem_model.set_inter_beat_gap_delay_policy(XIL_AXI_MEMORY_DELAY_FIXED);
  bias_axi.mem_model.set_inter_beat_gap(0);

  feature_axi.mem_model.set_inter_beat_gap_delay_policy(XIL_AXI_MEMORY_DELAY_FIXED);
  feature_axi.mem_model.set_inter_beat_gap(0);

  adj_axi.mem_model.set_inter_beat_gap_delay_policy(XIL_AXI_MEMORY_DELAY_FIXED);
  adj_axi.mem_model.set_inter_beat_gap(0);

endtask

/////////////////////////////////////////////////////////////////////////////////////////////////
// For each of the connected slave interfaces, Allow the memory model to insert any inter-beat
// gaps on the READ channel.
task automatic slv_random_delay_rvalid();
  $display("%t - Applying slv_random_delay_rvalid", $time);

  inst_axi.mem_model.set_inter_beat_gap_delay_policy(XIL_AXI_MEMORY_DELAY_RANDOM);
  inst_axi.mem_model.set_inter_beat_gap_range(0,10);

  weight_axi.mem_model.set_inter_beat_gap_delay_policy(XIL_AXI_MEMORY_DELAY_RANDOM);
  weight_axi.mem_model.set_inter_beat_gap_range(0,10);

  bias_axi.mem_model.set_inter_beat_gap_delay_policy(XIL_AXI_MEMORY_DELAY_RANDOM);
  bias_axi.mem_model.set_inter_beat_gap_range(0,10);

  feature_axi.mem_model.set_inter_beat_gap_delay_policy(XIL_AXI_MEMORY_DELAY_RANDOM);
  feature_axi.mem_model.set_inter_beat_gap_range(0,10);

  adj_axi.mem_model.set_inter_beat_gap_delay_policy(XIL_AXI_MEMORY_DELAY_RANDOM);
  adj_axi.mem_model.set_inter_beat_gap_range(0,10);

endtask

/////////////////////////////////////////////////////////////////////////////////////////////////
// Check to ensure, following reset the value of the register is 0.
// Check that only the width of the register bits can be written.
task automatic check_register_value(input bit [31:0] addr_in, input integer unsigned register_width, output bit error_found);
  bit [31:0] rddata;
  bit [31:0] mask_data;
  error_found = 0;
  if (register_width < 32) begin
    mask_data = (1 << register_width) - 1;
  end else begin
    mask_data = 32'hffffffff;
  end
  read_register(addr_in, rddata);
  if (rddata != 32'h0) begin
    $error("Initial value mismatch: A:0x%0x : Expected 0x%x -> Got 0x%x", addr_in, 0, rddata);
    error_found = 1;
  end
  blocking_write_register(addr_in, 32'hffffffff);
  read_register(addr_in, rddata);
  if (rddata != mask_data) begin
    $error("Initial value mismatch: A:0x%0x : Expected 0x%x -> Got 0x%x", addr_in, mask_data, rddata);
    error_found = 1;
  end
endtask


/////////////////////////////////////////////////////////////////////////////////////////////////
// For each of the scalar registers, check:
// * reset value
// * correct number bits set on a write
task automatic check_scalar_registers(output bit error_found);
  bit tmp_error_found = 0;
  error_found = 0;
  $display("%t : Checking post reset values of scalar registers", $time);

endtask

task automatic set_scalar_registers();
  $display("%t : Setting Scalar Registers registers", $time);

endtask

task automatic check_pointer_registers(output bit error_found);
  bit tmp_error_found = 0;
  ///////////////////////////////////////////////////////////////////////////
  //Check the reset states of the pointer registers.
  $display("%t : Checking post reset values of pointer registers", $time);

  ///////////////////////////////////////////////////////////////////////////
  //Write ID 0: inst_addr (0x010)
  check_register_value(32'h010, 32, tmp_error_found);
  error_found |= tmp_error_found;

  ///////////////////////////////////////////////////////////////////////////
  //Write ID 0: inst_addr (0x014)
  check_register_value(32'h014, 32, tmp_error_found);
  error_found |= tmp_error_found;

  ///////////////////////////////////////////////////////////////////////////
  //Write ID 1: weight_addr (0x01c)
  check_register_value(32'h01c, 32, tmp_error_found);
  error_found |= tmp_error_found;

  ///////////////////////////////////////////////////////////////////////////
  //Write ID 1: weight_addr (0x020)
  check_register_value(32'h020, 32, tmp_error_found);
  error_found |= tmp_error_found;

  ///////////////////////////////////////////////////////////////////////////
  //Write ID 2: bias_addr (0x028)
  check_register_value(32'h028, 32, tmp_error_found);
  error_found |= tmp_error_found;

  ///////////////////////////////////////////////////////////////////////////
  //Write ID 2: bias_addr (0x02c)
  check_register_value(32'h02c, 32, tmp_error_found);
  error_found |= tmp_error_found;

  ///////////////////////////////////////////////////////////////////////////
  //Write ID 3: feature_addr (0x034)
  check_register_value(32'h034, 32, tmp_error_found);
  error_found |= tmp_error_found;

  ///////////////////////////////////////////////////////////////////////////
  //Write ID 3: feature_addr (0x038)
  check_register_value(32'h038, 32, tmp_error_found);
  error_found |= tmp_error_found;

  ///////////////////////////////////////////////////////////////////////////
  //Write ID 4: adj_addr (0x040)
  check_register_value(32'h040, 32, tmp_error_found);
  error_found |= tmp_error_found;

  ///////////////////////////////////////////////////////////////////////////
  //Write ID 4: adj_addr (0x044)
  check_register_value(32'h044, 32, tmp_error_found);
  error_found |= tmp_error_found;

endtask

task automatic set_memory_pointers();
  ///////////////////////////////////////////////////////////////////////////
  //Randomly generate memory pointers.
  inst_addr_ptr = get_random_ptr();
  weight_addr_ptr = get_random_ptr();
  bias_addr_ptr = get_random_ptr();
  feature_addr_ptr = get_random_ptr();
  adj_addr_ptr = get_random_ptr();

  ///////////////////////////////////////////////////////////////////////////
  //Write ID 0: inst_addr (0x010) -> Randomized 4k aligned address (Global memory, lower 32 bits)
  write_register(32'h010, inst_addr_ptr[31:0]);

  ///////////////////////////////////////////////////////////////////////////
  //Write ID 0: inst_addr (0x014) -> Randomized 4k aligned address (Global memory, upper 32 bits)
  write_register(32'h014, inst_addr_ptr[63:32]);

  ///////////////////////////////////////////////////////////////////////////
  //Write ID 1: weight_addr (0x01c) -> Randomized 4k aligned address (Global memory, lower 32 bits)
  write_register(32'h01c, weight_addr_ptr[31:0]);

  ///////////////////////////////////////////////////////////////////////////
  //Write ID 1: weight_addr (0x020) -> Randomized 4k aligned address (Global memory, upper 32 bits)
  write_register(32'h020, weight_addr_ptr[63:32]);

  ///////////////////////////////////////////////////////////////////////////
  //Write ID 2: bias_addr (0x028) -> Randomized 4k aligned address (Global memory, lower 32 bits)
  write_register(32'h028, bias_addr_ptr[31:0]);

  ///////////////////////////////////////////////////////////////////////////
  //Write ID 2: bias_addr (0x02c) -> Randomized 4k aligned address (Global memory, upper 32 bits)
  write_register(32'h02c, bias_addr_ptr[63:32]);

  ///////////////////////////////////////////////////////////////////////////
  //Write ID 3: feature_addr (0x034) -> Randomized 4k aligned address (Global memory, lower 32 bits)
  write_register(32'h034, feature_addr_ptr[31:0]);

  ///////////////////////////////////////////////////////////////////////////
  //Write ID 3: feature_addr (0x038) -> Randomized 4k aligned address (Global memory, upper 32 bits)
  write_register(32'h038, feature_addr_ptr[63:32]);

  ///////////////////////////////////////////////////////////////////////////
  //Write ID 4: adj_addr (0x040) -> Randomized 4k aligned address (Global memory, lower 32 bits)
  write_register(32'h040, adj_addr_ptr[31:0]);

  ///////////////////////////////////////////////////////////////////////////
  //Write ID 4: adj_addr (0x044) -> Randomized 4k aligned address (Global memory, upper 32 bits)
  write_register(32'h044, adj_addr_ptr[63:32]);

endtask

task automatic backdoor_fill_memories();

  /////////////////////////////////////////////////////////////////////////////////////////////////
  // Backdoor fill the memory with the content.
  inst_axi_fill_memory(inst_addr_ptr, LP_MAX_LENGTH);

  /////////////////////////////////////////////////////////////////////////////////////////////////
  // Backdoor fill the memory with the content.
  weight_axi_fill_memory(weight_addr_ptr, LP_MAX_LENGTH);

  /////////////////////////////////////////////////////////////////////////////////////////////////
  // Backdoor fill the memory with the content.
  bias_axi_fill_memory(bias_addr_ptr, LP_MAX_LENGTH);

  /////////////////////////////////////////////////////////////////////////////////////////////////
  // Backdoor fill the memory with the content.
  feature_axi_fill_memory(feature_addr_ptr, LP_MAX_LENGTH);

  /////////////////////////////////////////////////////////////////////////////////////////////////
  // Backdoor fill the memory with the content.
  adj_axi_fill_memory(adj_addr_ptr, LP_MAX_LENGTH);

endtask

function automatic bit check_kernel_result();
  bit [31:0]        ret_rd_value = 32'h0;
  bit error_found = 0;
  integer error_counter;
  error_counter = 0;

  /////////////////////////////////////////////////////////////////////////////////////////////////
  // Checking memory connected to inst_axi
  for (longint unsigned slot = 0; slot < LP_MAX_LENGTH; slot++) begin
    ret_rd_value = inst_axi.mem_model.backdoor_memory_read_4byte(inst_addr_ptr + (slot * 4));
    if (slot < LP_MAX_TRANSFER_LENGTH) begin
      if (ret_rd_value != (slot + 1)) begin
        $error("Memory Mismatch: inst_axi : @0x%x : Expected 0x%x -> Got 0x%x ", inst_addr_ptr + (slot * 4), slot + 1, ret_rd_value);
        error_found |= 1;
        error_counter++;
      end
    end else begin
      if (ret_rd_value != slot) begin
        $error("Memory Mismatch: inst_axi : @0x%x : Expected 0x%x -> Got 0x%x ", inst_addr_ptr + (slot * 4), slot, ret_rd_value);
        error_found |= 1;
        error_counter++;
      end
    end
    if (error_counter > 5) begin
      $display("Too many errors found. Exiting check of inst_axi.");
      slot = LP_MAX_LENGTH;
    end
  end
  error_counter = 0;

  /////////////////////////////////////////////////////////////////////////////////////////////////
  // Checking memory connected to weight_axi
  for (longint unsigned slot = 0; slot < LP_MAX_LENGTH; slot++) begin
    ret_rd_value = weight_axi.mem_model.backdoor_memory_read_4byte(weight_addr_ptr + (slot * 4));
    if (slot < LP_MAX_TRANSFER_LENGTH) begin
      if (ret_rd_value != (slot + 1)) begin
        $error("Memory Mismatch: weight_axi : @0x%x : Expected 0x%x -> Got 0x%x ", weight_addr_ptr + (slot * 4), slot + 1, ret_rd_value);
        error_found |= 1;
        error_counter++;
      end
    end else begin
      if (ret_rd_value != slot) begin
        $error("Memory Mismatch: weight_axi : @0x%x : Expected 0x%x -> Got 0x%x ", weight_addr_ptr + (slot * 4), slot, ret_rd_value);
        error_found |= 1;
        error_counter++;
      end
    end
    if (error_counter > 5) begin
      $display("Too many errors found. Exiting check of weight_axi.");
      slot = LP_MAX_LENGTH;
    end
  end
  error_counter = 0;

  /////////////////////////////////////////////////////////////////////////////////////////////////
  // Checking memory connected to bias_axi
  for (longint unsigned slot = 0; slot < LP_MAX_LENGTH; slot++) begin
    ret_rd_value = bias_axi.mem_model.backdoor_memory_read_4byte(bias_addr_ptr + (slot * 4));
    if (slot < LP_MAX_TRANSFER_LENGTH) begin
      if (ret_rd_value != (slot + 1)) begin
        $error("Memory Mismatch: bias_axi : @0x%x : Expected 0x%x -> Got 0x%x ", bias_addr_ptr + (slot * 4), slot + 1, ret_rd_value);
        error_found |= 1;
        error_counter++;
      end
    end else begin
      if (ret_rd_value != slot) begin
        $error("Memory Mismatch: bias_axi : @0x%x : Expected 0x%x -> Got 0x%x ", bias_addr_ptr + (slot * 4), slot, ret_rd_value);
        error_found |= 1;
        error_counter++;
      end
    end
    if (error_counter > 5) begin
      $display("Too many errors found. Exiting check of bias_axi.");
      slot = LP_MAX_LENGTH;
    end
  end
  error_counter = 0;

  /////////////////////////////////////////////////////////////////////////////////////////////////
  // Checking memory connected to feature_axi
  for (longint unsigned slot = 0; slot < LP_MAX_LENGTH; slot++) begin
    ret_rd_value = feature_axi.mem_model.backdoor_memory_read_4byte(feature_addr_ptr + (slot * 4));
    if (slot < LP_MAX_TRANSFER_LENGTH) begin
      if (ret_rd_value != (slot + 1)) begin
        $error("Memory Mismatch: feature_axi : @0x%x : Expected 0x%x -> Got 0x%x ", feature_addr_ptr + (slot * 4), slot + 1, ret_rd_value);
        error_found |= 1;
        error_counter++;
      end
    end else begin
      if (ret_rd_value != slot) begin
        $error("Memory Mismatch: feature_axi : @0x%x : Expected 0x%x -> Got 0x%x ", feature_addr_ptr + (slot * 4), slot, ret_rd_value);
        error_found |= 1;
        error_counter++;
      end
    end
    if (error_counter > 5) begin
      $display("Too many errors found. Exiting check of feature_axi.");
      slot = LP_MAX_LENGTH;
    end
  end
  error_counter = 0;

  /////////////////////////////////////////////////////////////////////////////////////////////////
  // Checking memory connected to adj_axi
  for (longint unsigned slot = 0; slot < LP_MAX_LENGTH; slot++) begin
    ret_rd_value = adj_axi.mem_model.backdoor_memory_read_4byte(adj_addr_ptr + (slot * 4));
    if (slot < LP_MAX_TRANSFER_LENGTH) begin
      if (ret_rd_value != (slot + 1)) begin
        $error("Memory Mismatch: adj_axi : @0x%x : Expected 0x%x -> Got 0x%x ", adj_addr_ptr + (slot * 4), slot + 1, ret_rd_value);
        error_found |= 1;
        error_counter++;
      end
    end else begin
      if (ret_rd_value != slot) begin
        $error("Memory Mismatch: adj_axi : @0x%x : Expected 0x%x -> Got 0x%x ", adj_addr_ptr + (slot * 4), slot, ret_rd_value);
        error_found |= 1;
        error_counter++;
      end
    end
    if (error_counter > 5) begin
      $display("Too many errors found. Exiting check of adj_axi.");
      slot = LP_MAX_LENGTH;
    end
  end
  error_counter = 0;

  return(error_found);
endfunction

bit choose_pressure_type = 0;
bit axis_choose_pressure_type = 0;
bit [0-1:0] axis_tlast_received;

/////////////////////////////////////////////////////////////////////////////////////////////////
// Set up the kernel for operation and set the kernel START bit.
// The task will poll the DONE bit and check the results when complete.
task automatic multiple_iteration(input integer unsigned num_iterations, output bit error_found);
  error_found = 0;

  $display("Starting: multiple_iteration");
  for (integer unsigned iter = 0; iter < num_iterations; iter++) begin

    
    $display("Starting iteration: %d / %d", iter+1, num_iterations);
    RAND_WREADY_PRESSURE_FAILED: assert(std::randomize(choose_pressure_type));
    case(choose_pressure_type)
      0: slv_no_backpressure_wready();
      1: slv_random_backpressure_wready();
    endcase
    RAND_RVALID_PRESSURE_FAILED: assert(std::randomize(choose_pressure_type));
    case(choose_pressure_type)
      0: slv_no_delay_rvalid();
      1: slv_random_delay_rvalid();
    endcase

    set_scalar_registers();
    set_memory_pointers();
    backdoor_fill_memories();
    // Check that Kernel is IDLE before starting.
    poll_idle_register();
    ///////////////////////////////////////////////////////////////////////////
    //Start transfers
    blocking_write_register(KRNL_CTRL_REG_ADDR, CTRL_START_MASK);

    ctrl.wait_drivers_idle();
    ///////////////////////////////////////////////////////////////////////////
    //Wait for interrupt being asserted or poll done register
    @(posedge interrupt);

    ///////////////////////////////////////////////////////////////////////////
    // Service the interrupt
    service_interrupts();
    wait(interrupt == 0);

    ///////////////////////////////////////////////////////////////////////////
    error_found |= check_kernel_result()   ;

    $display("Finished iteration: %d / %d", iter+1, num_iterations);
  end
 endtask

/////////////////////////////////////////////////////////////////////////////////////////////////
//Instantiate AXI4 LITE VIP
initial begin : STIMULUS
  #200000;
  start_vips();
  check_scalar_registers(error_found);
  if (error_found == 1) begin
    $display( "Test Failed!");
    $finish();
  end

  check_pointer_registers(error_found);
  if (error_found == 1) begin
    $display( "Test Failed!");
    $finish();
  end

  enable_interrupts();

  multiple_iteration(1, error_found);
  if (error_found == 1) begin
    $display( "Test Failed!");
    $finish();
  end

  multiple_iteration(5, error_found);

  if (error_found == 1) begin
    $display( "Test Failed!");
    $finish();
  end else begin
    $display( "Test completed successfully");
  end
  $finish;
end

endmodule
`default_nettype wire

