// This is a generated file. Use and modify at your own risk.
//////////////////////////////////////////////////////////////////////////////// 
// Author: Kai Zhong
// Mail  : zhongkai2020@sina.com
// Date  : 2022.12.15
// Info  : generated by Vitis and nothing has been changed
//////////////////////////////////////////////////////////////////////////////// 
// default_nettype of none prevents implicit wire declaration.
`default_nettype none
`timescale 1 ns / 1 ps
// Top level of the kernel. Do not modify module name, parameters or ports.
module gnn_0 #(
  parameter integer C_S_AXI_CONTROL_ADDR_WIDTH = 12 ,
  parameter integer C_S_AXI_CONTROL_DATA_WIDTH = 32 ,
  parameter integer C_INST_AXI_ADDR_WIDTH      = 64 ,
  parameter integer C_INST_AXI_DATA_WIDTH      = 512,
  parameter integer C_WEIGHT_AXI_ADDR_WIDTH    = 64 ,
  parameter integer C_WEIGHT_AXI_DATA_WIDTH    = 512,
  parameter integer C_BIAS_AXI_ADDR_WIDTH      = 64 ,
  parameter integer C_BIAS_AXI_DATA_WIDTH      = 512,
  parameter integer C_FEATURE_AXI_ADDR_WIDTH   = 64 ,
  parameter integer C_FEATURE_AXI_DATA_WIDTH   = 512,
  parameter integer C_ADJ_AXI_ADDR_WIDTH       = 64 ,
  parameter integer C_ADJ_AXI_DATA_WIDTH       = 512
)
(
  // System Signals
  input  wire                                    ap_clk               ,
  input  wire                                    ap_rst_n             ,
  //  Note: A minimum subset of AXI4 memory mapped signals are declared.  AXI
  // signals omitted from these interfaces are automatically inferred with the
  // optimal values for Xilinx accleration platforms.  This allows Xilinx AXI4 Interconnects
  // within the system to be optimized by removing logic for AXI4 protocol
  // features that are not necessary. When adapting AXI4 masters within the RTL
  // kernel that have signals not declared below, it is suitable to add the
  // signals to the declarations below to connect them to the AXI4 Master.
  // 
  // List of ommited signals - effect
  // -------------------------------
  // ID - Transaction ID are used for multithreading and out of order
  // transactions.  This increases complexity. This saves logic and increases Fmax
  // in the system when ommited.
  // SIZE - Default value is log2(data width in bytes). Needed for subsize bursts.
  // This saves logic and increases Fmax in the system when ommited.
  // BURST - Default value (0b01) is incremental.  Wrap and fixed bursts are not
  // recommended. This saves logic and increases Fmax in the system when ommited.
  // LOCK - Not supported in AXI4
  // CACHE - Default value (0b0011) allows modifiable transactions. No benefit to
  // changing this.
  // PROT - Has no effect in current acceleration platforms.
  // QOS - Has no effect in current acceleration platforms.
  // REGION - Has no effect in current acceleration platforms.
  // USER - Has no effect in current acceleration platforms.
  // RESP - Not useful in most acceleration platforms.
  // 
  // AXI4 master interface inst_axi
  output wire                                    inst_axi_awvalid     ,
  input  wire                                    inst_axi_awready     ,
  output wire [C_INST_AXI_ADDR_WIDTH-1:0]        inst_axi_awaddr      ,
  output wire [8-1:0]                            inst_axi_awlen       ,
  output wire                                    inst_axi_wvalid      ,
  input  wire                                    inst_axi_wready      ,
  output wire [C_INST_AXI_DATA_WIDTH-1:0]        inst_axi_wdata       ,
  output wire [C_INST_AXI_DATA_WIDTH/8-1:0]      inst_axi_wstrb       ,
  output wire                                    inst_axi_wlast       ,
  input  wire                                    inst_axi_bvalid      ,
  output wire                                    inst_axi_bready      ,
  output wire                                    inst_axi_arvalid     ,
  input  wire                                    inst_axi_arready     ,
  output wire [C_INST_AXI_ADDR_WIDTH-1:0]        inst_axi_araddr      ,
  output wire [8-1:0]                            inst_axi_arlen       ,
  input  wire                                    inst_axi_rvalid      ,
  output wire                                    inst_axi_rready      ,
  input  wire [C_INST_AXI_DATA_WIDTH-1:0]        inst_axi_rdata       ,
  input  wire                                    inst_axi_rlast       ,
  // AXI4 master interface weight_axi
  output wire                                    weight_axi_awvalid   ,
  input  wire                                    weight_axi_awready   ,
  output wire [C_WEIGHT_AXI_ADDR_WIDTH-1:0]      weight_axi_awaddr    ,
  output wire [8-1:0]                            weight_axi_awlen     ,
  output wire                                    weight_axi_wvalid    ,
  input  wire                                    weight_axi_wready    ,
  output wire [C_WEIGHT_AXI_DATA_WIDTH-1:0]      weight_axi_wdata     ,
  output wire [C_WEIGHT_AXI_DATA_WIDTH/8-1:0]    weight_axi_wstrb     ,
  output wire                                    weight_axi_wlast     ,
  input  wire                                    weight_axi_bvalid    ,
  output wire                                    weight_axi_bready    ,
  output wire                                    weight_axi_arvalid   ,
  input  wire                                    weight_axi_arready   ,
  output wire [C_WEIGHT_AXI_ADDR_WIDTH-1:0]      weight_axi_araddr    ,
  output wire [8-1:0]                            weight_axi_arlen     ,
  input  wire                                    weight_axi_rvalid    ,
  output wire                                    weight_axi_rready    ,
  input  wire [C_WEIGHT_AXI_DATA_WIDTH-1:0]      weight_axi_rdata     ,
  input  wire                                    weight_axi_rlast     ,
  // AXI4 master interface bias_axi
  output wire                                    bias_axi_awvalid     ,
  input  wire                                    bias_axi_awready     ,
  output wire [C_BIAS_AXI_ADDR_WIDTH-1:0]        bias_axi_awaddr      ,
  output wire [8-1:0]                            bias_axi_awlen       ,
  output wire                                    bias_axi_wvalid      ,
  input  wire                                    bias_axi_wready      ,
  output wire [C_BIAS_AXI_DATA_WIDTH-1:0]        bias_axi_wdata       ,
  output wire [C_BIAS_AXI_DATA_WIDTH/8-1:0]      bias_axi_wstrb       ,
  output wire                                    bias_axi_wlast       ,
  input  wire                                    bias_axi_bvalid      ,
  output wire                                    bias_axi_bready      ,
  output wire                                    bias_axi_arvalid     ,
  input  wire                                    bias_axi_arready     ,
  output wire [C_BIAS_AXI_ADDR_WIDTH-1:0]        bias_axi_araddr      ,
  output wire [8-1:0]                            bias_axi_arlen       ,
  input  wire                                    bias_axi_rvalid      ,
  output wire                                    bias_axi_rready      ,
  input  wire [C_BIAS_AXI_DATA_WIDTH-1:0]        bias_axi_rdata       ,
  input  wire                                    bias_axi_rlast       ,
  // AXI4 master interface feature_axi
  output wire                                    feature_axi_awvalid  ,
  input  wire                                    feature_axi_awready  ,
  output wire [C_FEATURE_AXI_ADDR_WIDTH-1:0]     feature_axi_awaddr   ,
  output wire [8-1:0]                            feature_axi_awlen    ,
  output wire                                    feature_axi_wvalid   ,
  input  wire                                    feature_axi_wready   ,
  output wire [C_FEATURE_AXI_DATA_WIDTH-1:0]     feature_axi_wdata    ,
  output wire [C_FEATURE_AXI_DATA_WIDTH/8-1:0]   feature_axi_wstrb    ,
  output wire                                    feature_axi_wlast    ,
  input  wire                                    feature_axi_bvalid   ,
  output wire                                    feature_axi_bready   ,
  output wire                                    feature_axi_arvalid  ,
  input  wire                                    feature_axi_arready  ,
  output wire [C_FEATURE_AXI_ADDR_WIDTH-1:0]     feature_axi_araddr   ,
  output wire [8-1:0]                            feature_axi_arlen    ,
  input  wire                                    feature_axi_rvalid   ,
  output wire                                    feature_axi_rready   ,
  input  wire [C_FEATURE_AXI_DATA_WIDTH-1:0]     feature_axi_rdata    ,
  input  wire                                    feature_axi_rlast    ,
  // AXI4 master interface adj_axi
  output wire                                    adj_axi_awvalid      ,
  input  wire                                    adj_axi_awready      ,
  output wire [C_ADJ_AXI_ADDR_WIDTH-1:0]         adj_axi_awaddr       ,
  output wire [8-1:0]                            adj_axi_awlen        ,
  output wire                                    adj_axi_wvalid       ,
  input  wire                                    adj_axi_wready       ,
  output wire [C_ADJ_AXI_DATA_WIDTH-1:0]         adj_axi_wdata        ,
  output wire [C_ADJ_AXI_DATA_WIDTH/8-1:0]       adj_axi_wstrb        ,
  output wire                                    adj_axi_wlast        ,
  input  wire                                    adj_axi_bvalid       ,
  output wire                                    adj_axi_bready       ,
  output wire                                    adj_axi_arvalid      ,
  input  wire                                    adj_axi_arready      ,
  output wire [C_ADJ_AXI_ADDR_WIDTH-1:0]         adj_axi_araddr       ,
  output wire [8-1:0]                            adj_axi_arlen        ,
  input  wire                                    adj_axi_rvalid       ,
  output wire                                    adj_axi_rready       ,
  input  wire [C_ADJ_AXI_DATA_WIDTH-1:0]         adj_axi_rdata        ,
  input  wire                                    adj_axi_rlast        ,
  // AXI4-Lite slave interface
  input  wire                                    s_axi_control_awvalid,
  output wire                                    s_axi_control_awready,
  input  wire [C_S_AXI_CONTROL_ADDR_WIDTH-1:0]   s_axi_control_awaddr ,
  input  wire                                    s_axi_control_wvalid ,
  output wire                                    s_axi_control_wready ,
  input  wire [C_S_AXI_CONTROL_DATA_WIDTH-1:0]   s_axi_control_wdata  ,
  input  wire [C_S_AXI_CONTROL_DATA_WIDTH/8-1:0] s_axi_control_wstrb  ,
  input  wire                                    s_axi_control_arvalid,
  output wire                                    s_axi_control_arready,
  input  wire [C_S_AXI_CONTROL_ADDR_WIDTH-1:0]   s_axi_control_araddr ,
  output wire                                    s_axi_control_rvalid ,
  input  wire                                    s_axi_control_rready ,
  output wire [C_S_AXI_CONTROL_DATA_WIDTH-1:0]   s_axi_control_rdata  ,
  output wire [2-1:0]                            s_axi_control_rresp  ,
  output wire                                    s_axi_control_bvalid ,
  input  wire                                    s_axi_control_bready ,
  output wire [2-1:0]                            s_axi_control_bresp  ,
  output wire                                    interrupt            
);

///////////////////////////////////////////////////////////////////////////////
// Local Parameters
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// Wires and Variables
///////////////////////////////////////////////////////////////////////////////
(* DONT_TOUCH = "yes" *)
reg                                 areset                         = 1'b0;
wire                                ap_start                      ;
wire                                ap_idle                       ;
wire                                ap_done                       ;
wire                                ap_ready                      ;
wire [64-1:0]                       inst_addr                     ;
wire [64-1:0]                       weight_addr                   ;
wire [64-1:0]                       bias_addr                     ;
wire [64-1:0]                       feature_addr                  ;
wire [64-1:0]                       adj_addr                      ;

// Register and invert reset signal.
always @(posedge ap_clk) begin
  areset <= ~ap_rst_n;
end

///////////////////////////////////////////////////////////////////////////////
// Begin control interface RTL.  Modifying not recommended.
///////////////////////////////////////////////////////////////////////////////


// AXI4-Lite slave interface
gnn_0_control_s_axi #(
  .C_S_AXI_ADDR_WIDTH ( C_S_AXI_CONTROL_ADDR_WIDTH ),
  .C_S_AXI_DATA_WIDTH ( C_S_AXI_CONTROL_DATA_WIDTH )
)
inst_control_s_axi (
  .ACLK         ( ap_clk                ),
  .ARESET       ( areset                ),
  .ACLK_EN      ( 1'b1                  ),
  .AWVALID      ( s_axi_control_awvalid ),
  .AWREADY      ( s_axi_control_awready ),
  .AWADDR       ( s_axi_control_awaddr  ),
  .WVALID       ( s_axi_control_wvalid  ),
  .WREADY       ( s_axi_control_wready  ),
  .WDATA        ( s_axi_control_wdata   ),
  .WSTRB        ( s_axi_control_wstrb   ),
  .ARVALID      ( s_axi_control_arvalid ),
  .ARREADY      ( s_axi_control_arready ),
  .ARADDR       ( s_axi_control_araddr  ),
  .RVALID       ( s_axi_control_rvalid  ),
  .RREADY       ( s_axi_control_rready  ),
  .RDATA        ( s_axi_control_rdata   ),
  .RRESP        ( s_axi_control_rresp   ),
  .BVALID       ( s_axi_control_bvalid  ),
  .BREADY       ( s_axi_control_bready  ),
  .BRESP        ( s_axi_control_bresp   ),
  .interrupt    ( interrupt             ),
  .ap_start     ( ap_start              ),
  .ap_done      ( ap_done               ),
  .ap_ready     ( ap_ready              ),
  .ap_idle      ( ap_idle               ),
  .inst_addr    ( inst_addr             ),
  .weight_addr  ( weight_addr           ),
  .bias_addr    ( bias_addr             ),
  .feature_addr ( feature_addr          ),
  .adj_addr     ( adj_addr              )
);

///////////////////////////////////////////////////////////////////////////////
// Add kernel logic here.  Modify/remove example code as necessary.
///////////////////////////////////////////////////////////////////////////////

// Example RTL block.  Remove to insert custom logic.
gnn_0_example #(
  .C_INST_AXI_ADDR_WIDTH    ( C_INST_AXI_ADDR_WIDTH    ),
  .C_INST_AXI_DATA_WIDTH    ( C_INST_AXI_DATA_WIDTH    ),
  .C_WEIGHT_AXI_ADDR_WIDTH  ( C_WEIGHT_AXI_ADDR_WIDTH  ),
  .C_WEIGHT_AXI_DATA_WIDTH  ( C_WEIGHT_AXI_DATA_WIDTH  ),
  .C_BIAS_AXI_ADDR_WIDTH    ( C_BIAS_AXI_ADDR_WIDTH    ),
  .C_BIAS_AXI_DATA_WIDTH    ( C_BIAS_AXI_DATA_WIDTH    ),
  .C_FEATURE_AXI_ADDR_WIDTH ( C_FEATURE_AXI_ADDR_WIDTH ),
  .C_FEATURE_AXI_DATA_WIDTH ( C_FEATURE_AXI_DATA_WIDTH ),
  .C_ADJ_AXI_ADDR_WIDTH     ( C_ADJ_AXI_ADDR_WIDTH     ),
  .C_ADJ_AXI_DATA_WIDTH     ( C_ADJ_AXI_DATA_WIDTH     )
)
inst_example (
  .ap_clk              ( ap_clk              ),
  .ap_rst_n            ( ap_rst_n            ),
  .inst_axi_awvalid    ( inst_axi_awvalid    ),
  .inst_axi_awready    ( inst_axi_awready    ),
  .inst_axi_awaddr     ( inst_axi_awaddr     ),
  .inst_axi_awlen      ( inst_axi_awlen      ),
  .inst_axi_wvalid     ( inst_axi_wvalid     ),
  .inst_axi_wready     ( inst_axi_wready     ),
  .inst_axi_wdata      ( inst_axi_wdata      ),
  .inst_axi_wstrb      ( inst_axi_wstrb      ),
  .inst_axi_wlast      ( inst_axi_wlast      ),
  .inst_axi_bvalid     ( inst_axi_bvalid     ),
  .inst_axi_bready     ( inst_axi_bready     ),
  .inst_axi_arvalid    ( inst_axi_arvalid    ),
  .inst_axi_arready    ( inst_axi_arready    ),
  .inst_axi_araddr     ( inst_axi_araddr     ),
  .inst_axi_arlen      ( inst_axi_arlen      ),
  .inst_axi_rvalid     ( inst_axi_rvalid     ),
  .inst_axi_rready     ( inst_axi_rready     ),
  .inst_axi_rdata      ( inst_axi_rdata      ),
  .inst_axi_rlast      ( inst_axi_rlast      ),
  .weight_axi_awvalid  ( weight_axi_awvalid  ),
  .weight_axi_awready  ( weight_axi_awready  ),
  .weight_axi_awaddr   ( weight_axi_awaddr   ),
  .weight_axi_awlen    ( weight_axi_awlen    ),
  .weight_axi_wvalid   ( weight_axi_wvalid   ),
  .weight_axi_wready   ( weight_axi_wready   ),
  .weight_axi_wdata    ( weight_axi_wdata    ),
  .weight_axi_wstrb    ( weight_axi_wstrb    ),
  .weight_axi_wlast    ( weight_axi_wlast    ),
  .weight_axi_bvalid   ( weight_axi_bvalid   ),
  .weight_axi_bready   ( weight_axi_bready   ),
  .weight_axi_arvalid  ( weight_axi_arvalid  ),
  .weight_axi_arready  ( weight_axi_arready  ),
  .weight_axi_araddr   ( weight_axi_araddr   ),
  .weight_axi_arlen    ( weight_axi_arlen    ),
  .weight_axi_rvalid   ( weight_axi_rvalid   ),
  .weight_axi_rready   ( weight_axi_rready   ),
  .weight_axi_rdata    ( weight_axi_rdata    ),
  .weight_axi_rlast    ( weight_axi_rlast    ),
  .bias_axi_awvalid    ( bias_axi_awvalid    ),
  .bias_axi_awready    ( bias_axi_awready    ),
  .bias_axi_awaddr     ( bias_axi_awaddr     ),
  .bias_axi_awlen      ( bias_axi_awlen      ),
  .bias_axi_wvalid     ( bias_axi_wvalid     ),
  .bias_axi_wready     ( bias_axi_wready     ),
  .bias_axi_wdata      ( bias_axi_wdata      ),
  .bias_axi_wstrb      ( bias_axi_wstrb      ),
  .bias_axi_wlast      ( bias_axi_wlast      ),
  .bias_axi_bvalid     ( bias_axi_bvalid     ),
  .bias_axi_bready     ( bias_axi_bready     ),
  .bias_axi_arvalid    ( bias_axi_arvalid    ),
  .bias_axi_arready    ( bias_axi_arready    ),
  .bias_axi_araddr     ( bias_axi_araddr     ),
  .bias_axi_arlen      ( bias_axi_arlen      ),
  .bias_axi_rvalid     ( bias_axi_rvalid     ),
  .bias_axi_rready     ( bias_axi_rready     ),
  .bias_axi_rdata      ( bias_axi_rdata      ),
  .bias_axi_rlast      ( bias_axi_rlast      ),
  .feature_axi_awvalid ( feature_axi_awvalid ),
  .feature_axi_awready ( feature_axi_awready ),
  .feature_axi_awaddr  ( feature_axi_awaddr  ),
  .feature_axi_awlen   ( feature_axi_awlen   ),
  .feature_axi_wvalid  ( feature_axi_wvalid  ),
  .feature_axi_wready  ( feature_axi_wready  ),
  .feature_axi_wdata   ( feature_axi_wdata   ),
  .feature_axi_wstrb   ( feature_axi_wstrb   ),
  .feature_axi_wlast   ( feature_axi_wlast   ),
  .feature_axi_bvalid  ( feature_axi_bvalid  ),
  .feature_axi_bready  ( feature_axi_bready  ),
  .feature_axi_arvalid ( feature_axi_arvalid ),
  .feature_axi_arready ( feature_axi_arready ),
  .feature_axi_araddr  ( feature_axi_araddr  ),
  .feature_axi_arlen   ( feature_axi_arlen   ),
  .feature_axi_rvalid  ( feature_axi_rvalid  ),
  .feature_axi_rready  ( feature_axi_rready  ),
  .feature_axi_rdata   ( feature_axi_rdata   ),
  .feature_axi_rlast   ( feature_axi_rlast   ),
  .adj_axi_awvalid     ( adj_axi_awvalid     ),
  .adj_axi_awready     ( adj_axi_awready     ),
  .adj_axi_awaddr      ( adj_axi_awaddr      ),
  .adj_axi_awlen       ( adj_axi_awlen       ),
  .adj_axi_wvalid      ( adj_axi_wvalid      ),
  .adj_axi_wready      ( adj_axi_wready      ),
  .adj_axi_wdata       ( adj_axi_wdata       ),
  .adj_axi_wstrb       ( adj_axi_wstrb       ),
  .adj_axi_wlast       ( adj_axi_wlast       ),
  .adj_axi_bvalid      ( adj_axi_bvalid      ),
  .adj_axi_bready      ( adj_axi_bready      ),
  .adj_axi_arvalid     ( adj_axi_arvalid     ),
  .adj_axi_arready     ( adj_axi_arready     ),
  .adj_axi_araddr      ( adj_axi_araddr      ),
  .adj_axi_arlen       ( adj_axi_arlen       ),
  .adj_axi_rvalid      ( adj_axi_rvalid      ),
  .adj_axi_rready      ( adj_axi_rready      ),
  .adj_axi_rdata       ( adj_axi_rdata       ),
  .adj_axi_rlast       ( adj_axi_rlast       ),
  .ap_start            ( ap_start            ),
  .ap_done             ( ap_done             ),
  .ap_idle             ( ap_idle             ),
  .ap_ready            ( ap_ready            ),
  .inst_addr           ( inst_addr           ),
  .weight_addr         ( weight_addr         ),
  .bias_addr           ( bias_addr           ),
  .feature_addr        ( feature_addr        ),
  .adj_addr            ( adj_addr            )
);

endmodule
`default_nettype wire
